### ISSUE TITLE
Community partner image sizes are not proper 

### ISSUE THREAD

**Issue by Suryanshomar7240** [GDSC-IIIT-Kalyani/Winter-of-Code-3.0-frontend#100]
![image](https://user-images.githubusercontent.com/76695520/208904921-9a1cc07d-7ff5-437b-962d-3d59f2237963.png)

**Comment by Rishav1707** [comment]
I think the image is in the proper size, please recheck your issue.

**Comment by halyris** [comment]
Fixed in #103.
