### ISSUE TITLE
First page 

### ISSUE THREAD

**Issue by Suryanshomar7240** [GDSC-IIIT-Kalyani/Winter-of-Code-3.0-frontend#101]
- [ ] birds and clouds are missing
- [ ] moving the first page assets from firebase bucket to asset folder 
![image](https://user-images.githubusercontent.com/76695520/208905417-22da5d43-fd04-4d30-b51f-f95340511f67.png)

- [ ] in mobile view "Apply with Devfolio" button should be in page
![image](https://user-images.githubusercontent.com/76695520/208905578-5a29dd69-d69b-4b90-bba4-8d3a56a4151f.png)

**Comment by iamnicky** [comment]
I want to work on this issue and @Suryanshomar7240

**Comment by Suryanshomar7240** [comment]
Sure @iamnicky

**Comment by Suryanshomar7240** [comment]
@iamnicky any updates?

**Comment by withgaurav** [comment]
I want to work on this issue @Suryanshomar7240

**Comment by Suryanshomar7240** [comment]
please finish as soon as possible @iamnicky I have already assigned you the issue :)

**Comment by Suryanshomar7240** [comment]
You can also work on this @withgaurav

**Comment by withgaurav** [comment]
Can you please give me your any social media or any platform where I can contact you.

**Comment by Suryanshomar7240** [comment]
you can join our discord channel https://discord.gg/5n3yPJv4RY

**Comment by withgaurav** [comment]
![image](https://user-images.githubusercontent.com/76643106/212545087-42109d6e-2b44-431a-8211-424d2c2658be.png)

you please tell me!! can I make a new button or should I make the same button as it was there in the mobile view's nav bar. I am unable to find the code for apply with Devfolio button in whole css and js which are present in github. Also I am unable to find you in discord I have joined the channel before
