### ISSUE TITLE
contributing.md file not found

### ISSUE THREAD

**Issue by withgaurav** [GDSC-IIIT-Kalyani/Winter-of-Code-3.0-frontend#126]
![image](https://user-images.githubusercontent.com/76643106/212464049-4385fcec-4993-4fc6-b0d6-67f877b9bd9e.png)

Page not found error while opening contribution guidelines in readme.md

**Comment by withgaurav** [comment]
Can I fix this issue? @Suryanshomar7240

**Comment by Suryanshomar7240** [comment]
Sure!
