### ISSUE TITLE
Improve ui of Registration form

### ISSUE THREAD

**Issue by HamdaanAliQuatil** [GDSC-IIIT-Kalyani/Winter-of-Code-3.0-frontend#33]
- [ ]  update the header it is looking a little weird
- [x] fish animation will not appear in the top layer
![image](https://user-images.githubusercontent.com/76695520/200173967-cc6de07c-d4aa-4294-9547-35ee036cc026.png)

**Comment by ARYA-RAY** [comment]
@HamdaanAliQuatil can u assign me this issue ?

**Comment by Suryanshomar7240** [comment]
yeah sure @ARYA-RAY
