### ISSUE TITLE
Small font size of timeline text

### ISSUE THREAD

**Issue by Gaurav-Verma07** [GDSC-IIIT-Kalyani/Winter-of-Code-3.0-frontend#86]
Hiii, I think the text in timeline section is way too small and that needs to be corrected. Since I want to contribute to the project as well.
So please assign this issue to me.

![image](https://user-images.githubusercontent.com/63046396/207139113-bc6bca4d-6d49-483f-aeac-6640b7aa8278.png)

**Comment by Suryanshomar7240** [comment]
Sure @Gaurav-Verma07
